"""empty message

Revision ID: 849525a361e9
Revises: 32ce4bac9b8b
Create Date: 2024-09-04 15:38:13.937156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849525a361e9'
down_revision = '32ce4bac9b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('module_name', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['display_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('module_name')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
